
function a = figureDate()
    a = annotation('textbox',[.1 .1 .1 .1],...
        'Units','pixel',...
        'Position', [1 10 80 12],...
        'FitBoxToText','off',...
        'String',date(),...
        'Interpreter', 'none',...
        'LineStyle','none');
end